# Generated by Django 3.2.5 on 2023-07-01 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ahorros', '0003_alter_ahorros_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorros',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahorros', to=settings.AUTH_USER_MODEL),
        ),
    ]
